use_frameworks!
platform :ios, '12.0'

target 'NSAttributedString-Utils_Example' do
  pod 'NSAttributedString-Utils', :path => '../'

  target 'NSAttributedString-Utils_Tests' do
    inherit! :search_paths

    
  end
end
